apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  labels:
    app: cnkt-event-listener
  name: cnkt-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
  - name: mq-qm01-dev
    interceptors:
      - ref:
          name: "cel"
        params:
        - name: "filter"
          value: "header.match('X-GitHub-Event', 'push') && body.ref == 'refs/heads/qm1-sbybee-tutorial' && body.repository.full_name == 'sbybee-tutorial/mq-qm01'"
    bindings:
      - ref: cnkt-trigger-binding
    template:
      ref: mq-qm-dev
  - name: mq-spring-app-dev
    interceptors:
      - ref:
          name: "cel"
        params:
        - name: "filter"
          value: "header.match('X-GitHub-Event', 'push') && body.ref == 'refs/heads/mq-spring-sbybee-tutorial' && body.repository.full_name == 'sbybee-tutorial/mq-spring-app'"
    bindings:
      - ref: cnkt-trigger-binding
    template:
      ref: mq-spring-app-dev
